# Generated by Django 5.2.8 on 2025-11-22 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="password_hash",
            field=models.CharField(default=123456, max_length=255),
            preserve_default=False,
        ),
    ]
