# Generated by Django 5.2.8 on 2025-11-23 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_password_hash"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="role_id",
            new_name="role",
        ),
    ]
